onlyBuiltDependencies:
  - '@prisma/engines'
  - bigint-buffer
  - blake-hash
  - bufferutil
  - esbuild
  - prisma
  - protobufjs
  - sharp
  - tiny-secp256k1
  - usb
  - utf-8-validate

patchedDependencies:
  bigint-buffer@1.1.5: patches/bigint-buffer@1.1.5.patch
